services:
  # The OTL collector reading the otel-collector-config.yml file.
  # It exposes only the 4317 port to collect OTLP telemetry over gRPC.
  # Go to otel-collector-config.yml to see how it is configured.
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.121.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver

  # The Jaeger all-in-one backend. It is composed of:
  #   - Jaeger collector: receives incoming trace data from applications and writes it into a storage backend.
  #   - Jaeger query: serves the APIs and the user interface for querying and visualizing traces.
  # See more at: https://www.jaegertracing.io/docs/2.3/architecture/
  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    ports:
      - "16686:16686" # Jaeger query (UI)

  # The Prometheus back-end.
  # It read prometheus.yml configuration and exposes the port 9090 to access its UI.
  prometheus:
    image: bitnami/prometheus:2.55.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
