# Configures otel-collector receivers.
# They are not active unless listed in service.pipelines configuration below.
receivers:
  otlp:
    # Configures a receiver endpoint at port 4317 through gRPC protocol.
    # This is the endpoint the API must target to send telemetry data.
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

# Configures otel-collector exporters.
# They are not active unless listed in service.pipelines configuration below.
exporters:
  # Configures an OTLP exporter pointing to jaeger service declared in docker-compose.yml to port 4317.
  # The Jaeger service exposes a 4317 port listening for OTLP telemetry through gRPC.
  # This is a push-based telemetry gathering strategy.
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  # Configures a "/metrics" endpoint listening at 9090 for Prometheus pull-based telemetry gathering.
  prometheus:
    endpoint: "0.0.0.0:9090"

# Declares all actives pipelines.
service:
  pipelines:
    # Declares a pipeline specific to traces.
    traces:
      # Chose receiver.otlp receiver as trace receiver. There may be multiple receivers.
      receivers: [otlp]
      # Chose receiver.otlp exporter as trace receiver. There may be multiple exporters.
      exporters: [otlp]

    # Declares a pipeline specific to metrics.
    metrics:
      # Chose receiver.otlp receiver as metrics receiver. There may be multiple receivers.
      receivers: [otlp]
      # Chose receiver.prometheus exporter as metrics receiver. There may be multiple exporters.
      exporters: [prometheus]
